apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    org: cloudacademy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      org: cloudacademy
  template:
    metadata:
      labels:
        app: api
        org: cloudacademy
    spec:
      containers:
      - name: api
        image: cloudacademydevops/api-metrics
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
    org: cloudacademy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "5000"
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: api
    org: cloudacademy
  type: NodePort

The api.yml file contains the Kubernetes resources that will be created for the API when deployed into the cluster. In particular note the following:

Lines 1-25: API Deployment containing 2 pods
Line 22: Pods are based off the container image cloudacademydevops/app-metrics
Lines 27-46: API Service - loadbalances traffic across the 2 API Deployment pods
Lines 34-37: API Service is annotated to ensure that the Prometheus scraper will automatically discover the API pods behind it. Prometheus will then collect their metrics from the discovered targets
